baseURL = "https://mogeko.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
 languageCode = "cn-ZH" # 博客的语言。有点主题没有做国际化优化，菜单等没有翻译成中文就不要太较真了
title = "Mogeko`s Blog" # 浏览器的标题
copyright = "" # 版权说明
theme = "hugo-hello-programmer-theme" # 主题 (需要自己下载)

# Google 统计
googleAnalytics = "UA-104502658-1" # Google 统计 id

# 代码高亮
# Hugo 使用内置的 Chroma 提供代码高亮，详情：http://gohugo.io/content-management/syntax-highlighting/
#pygmentsUseClassic=true # 使用 Pygments 提供代码高亮
pygmentsCodeFences = false # 开启代码高亮
pygmentsStyle = "monokai" # 代码高亮主题，可供选择的主题有：native、vim、fruity、monokai
pygmentsUseClasses=true # 使用自定义的代码高亮样式
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[author]
  author = "Mogeko" # 作者名字
  email = "zhengjunyi@live.com"

[params]
  since = "2017" # 站点建立时间
  copyrightyear = "2018" # Copyright 年份 (不好解释，反正填今年就对了)
  description = "Mogeko 的个人博客" # (Meta) 描述

  # 以下设置需要自己改代码，详细步骤我以后会出文章详细说明的
  ## 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  toc = false # 是否开启目录
  #mathjax = false # 是否使用mathjax（数学公式）
  #contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  ## 评论系统。
  [params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientId = "936cecdd2ab935870ca5" # Your client ID
    clientSecret = "39cfc7a3cb9a974b6609f3fdaa637e2917e3e40a" # Your client secret
    repo = "mogeko.github.io" # The repo to store comments
    owner = "Mogeko" # Your GitHub ID
    admin= "Mogeko" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.